server:
  port: 0
spring:
  application:
    name: ms-tickets
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      database: dashboard
      username: root
      password: secret
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
  instance:
    non-secure-port-enabled: true
    secure-port-enabled: false
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: '*'

cloud:
  aws:
    credentials:
      access-key: KEY
      secret-key: SECRET