server:
  port: 0
spring:
  application:
    name: ms-tickets

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
  instance:
    non-secure-port-enabled: true
    secure-port-enabled: false
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: '*'